Lim-JiSeon/HufsClub

.gitignore, README.md, backend/models/clubModel.js, backend/models/userModel.js, backend/package.json, package.json
- clubSChema에 views(조회수) 변수 추가
- clubModel파일의 recruitSchema에 지원 링크를 담을 applyUrl변수를 추가하여 way는 지원 링크가 아닌 모집 방식(ex)구글폼 지원 후 면접)을 의미하도록 함.
- userSchema에 email 변수 추가
=> email, applyUrl, views 변수 추가

frontend/src/components/AreaComponent.jsx, frontend/src/components/Button.js, frontend/src/components/ErrorText.js, frontend/src/components/Input.js, frontend/src/components/InputComponent.jsx, frontend/src/components/IntroComponent.jsx, frontend/src/components/LoginComponent.jsx, frontend/src/components/LoginForm.js, frontend/src/components/MainComponent.jsx, frontend/src/components/MyPageComponent.jsx, frontend/src/components/SignUpComponent.jsx, frontend/src/hooks/useForm.js, frontend/src/index.css, frontend/src/pages/LoginPage.jsx, frontend/src/pages/MainPage.jsx
=> [FEAT] Login page 구현 완료

backend/package.json, backend/routes/userRoutes.js, backend/utili.js
지난 한 주간 비밀번호 찾기 api를 작성하려 애썼지만 잘 안돼서 아직 완성하지 못했습니다. 
작업하다가 깨달았는데 Front-end에서 비밀번호 reset페이지를 만들어주셔야 할 것 같습니다.(일단 제가 api 완성하고 나면 나중에 그에 맞게 페이지 만들어주시면 될 것 같습니다!)
<작업한 내용>
- 가비아 홈페이지에서 hufsclub.site 도메인 구매(유효 기간 1년)
- test용 API key 생성
- env파일에 MAILGUN_API_KEY와 MAILGUN_DOMAIN 변수 추가(변수 값이 달라질 수 있어서 나중에 알려드리겠습니다.)
- 이메일 전송에 필요한 함수 작성
=> 비밀번호 찾기(작업진행중)

frontend/src/api/search.js, frontend/src/pages/AreaPage.jsx
<동아리명 검색 페이지>
- 동아리명 검색 api 연결 성공
- 동아리명 입력 받아 데이터를 불러오는 로직 구현 완료
남은 작업
- ui 디자인
=> 검색 api 연결 및 로직 구현

backend/models/userModel.js, backend/package.json, backend/routes/userRoutes.js, backend/utili.js
#작업한 내용
- 비밀번호 찾기용으로 발송할 이메일 계정 생성
- .env파일에 변수 추가(카톡으로 보내드리겠습니다. 타인에게 공개하지 않도록 주의해주세요!)
- 로그인 페이지: 아이디, 비밀번호 찾기 Controller 및 API 명세서 작성(userModel에 아이디, 비번 찾기에 필요한 resetToken 변수와 verificationCode 변수 추가)
*패키지 추가했습니다. backend 폴더로 이동해서 npm i 명령어 실행해주세요!
*아이디 찾기 과정: 네이버의 아이디 찾기(이메일로 인증) 방식을 참고했습니다. 
아이디 찾기를 누르면 이름, 이메일 주소, 인증 번호를 입력하는 칸
과 인증 번호 받기 버튼, 다음 버튼이 있는 페이지가 있으면 됩니다.    
1. 이름과 이메일 주소 입력 후, 인증 번호 받기 버튼 클릭
2. 사용자의 이메일로 인증 번호가 전송됨.
3. 사용자가 인증 번호를 입력
4. 다음 버튼을 누르면 백엔드에서 인증 번호가 맞는지 확인하고 맞으
면 아이디(학번)을 res로 보내주는데, 이 아이디를 다음 버튼을 눌러
서 넘어간 새 페이지 화면에 보여주면 된다. 
아이디 찾기와 관련된 api가 2개입니다. 1번, 2번의 과정은 아이디 찾
기(메일 전송) api와 연결해주시면 됩니다. 그리고 3, 4번의 과정은 아
이디 확인(인증 번호 확인) api와 연결해주시면 됩니다.
*비밀번호 찾기 과정: 마찬가지로 2개의 api가 존재합니다. 
1. 사용자의 (회원가입 시 입력한) 메일 주소를 받는다.
2. 메일로 비밀번호를 재설정할 수 있는 링크를 보내준다. 
3. 해당 링크의 페이지로 가서 …
=> 아이디 찾기, 비밀번호 찾기 구현 완료

frontend/src/api/findId.js, frontend/src/api/findPw.js, frontend/src/components/FindIdForm.js, frontend/src/components/FindPwForm.js
- 아이디 찾기 및 비밀번호 찾기 로직 구현 완료
- 디자인 수정 완료
- 이벤트 처리 완료
- api 연결 완료
문제 사항
- api 연결시 404 에러 발생
- 값이 잘못 전달된 걸까 싶어 직접적으로 api에 명세서에 있는 예시 값을 줬지만 404 에러가 그대로 발생
- 회원가입 후 새로운 회원 계정으로 값을 전달해도 404 에러 발생
- 원인으로 name과 email이 잘못되어 404 에러를 res로 주는 것으로 추측
서버에 김철수 이름으로 된 계정이 rac8793@naver.com 이 맞는지 확인 부탁드립니다.
추가로 임지선 dpf226@naver.com이 추가되었는지도 확인 부탁드립니다. 
이 에러는 다시 확인해본 뒤 정확한 원인 파악 후 해결할 예정입니다. 
참고로 백엔드 라우터에서 해당 코드에서 console.log로 출력해본 결과 req.body에 정상적으로 값이 전달된 것을 볼 수 있었습니다.
```
req =  { username: '김철수', email: 'rac8793@naver.com' }
user =  null
```
다만 user을 console.log로 출력했을 때에는 null이 나왔습니다. 여기서 user란 userRouter 파일의 225 줄을 의미합니다.
```js
const user = await User.findOne({ username: req.body.username, email: req.body.email });
```
직접적으로 테스트하기 위해 값을 넣은 경우 
다음 코드와 같이 예시 값을 직접적으로 넣어줬음에도 404 에러 발생 
```js
import …
```
=> 아이디 및 비밀번호 찾기

frontend/src/api/login.js, frontend/src/components/LoginForm.js, frontend/src/constants/api.js, frontend/src/hooks/useForm.js
로그인 작업 구현에서 잘못 구현한 부분이 있어 리팩토링 진행했습니다. 
- api 불러오는 로직 수정
- session storage에 토큰, id를 저장
- 로그인 후 메인 페이지로 이동하는 로직 추가
- 아이디 또는 비번이 틀릴 경우 처리하는 로직 추가
=> refactoring: 로그인 로직 리팩토링

frontend/src/api/signup.js, frontend/src/components/SignUpForm.js, frontend/src/constants/api.js, frontend/src/hooks/useForm.js
회원가입 작업 구현에서 잘못 구현한 부분이 있어 리팩토링 진행했습니다.
- api 불러오는 로직 수정
- 다 입력하기 전까지는 페이지 이동 막는 로직 추가
- 회원가입 후 로그인 페이지로 이동하는 로직 추가
- 회원가입 성공 및 실패 알림 로직 추가
=> refactoring: 회원가입 로직 리팩토링

frontend/src/api/search.js, frontend/src/api/search/content.js, frontend/src/api/search/search.js, frontend/src/api/search/topic.js, frontend/src/components/ClubGrid.js, frontend/src/components/SearchBar.js, frontend/src/components/func/ClubItem.js, frontend/src/components/func/Select.js, frontend/src/constants/api.js, frontend/src/index.js, frontend/src/pages/AreaPage.jsx
검색 페이지 관련해서 수정된 사항들을 반영했습니다.
- 검색 필터링 추가(이름, 주제, 내용)
- 각 api 로직 추가
- 검색 결과물 리스트 컴포넌트 추가
- 검색 결과물 아이템 컴포넌트 추가
<추가 작업>
- 검색 결과 가져오기 성공
- 검색 결과를 화면에 뿌려주는데 에러가 있어 이 부분 해결 중(새로 브랜치 파서 작업할 예정)
=> feat: search 페이지 수정

backend/routes/clubRoutes.js
#작업한 내용
- 동아리 활동 검색 controller 및 API 명세서 수정 완료
지난주에 데이터베이스의 clubModel의 activity를 단락 별로 묶어서 저장하도록 바꿈에 따라 동아리 활동 검색 controller가               
수정이 필요해져서 수정 완료했습니다. 
- 좋아요 추가 API 명세서 작성
#작업할 내용
- 좋아요 삭제 controller 및 api명세서 작성
- 동아리 글 작성 버튼 누를 때 이미 글 존재하는지 검사
- 세부 동아리 정보 페이지에 수정 및 삭제 api 구현하기(회장 여부는 프론트에서 검사)
- 동아리 글 작성(topic은 동아리 글 작성자가 쉼표로 구분해서 입력하면 해쉬태그 적용해서 데이터베이스에 저장-백엔드에서 구현), 수정, 삭제 api
=> 활동 검색 controller 수정 완료

frontend/src/api/findId.js, frontend/src/components/FindIdForm.js, frontend/src/components/SignUpForm.js, frontend/src/components/func/Input.js, frontend/src/hooks/useForm.js
구현 내용
- 인증 번호를 메일로 보낼 경우 알림 창을 띄워 사용자가 인증번호가 메일로 보내졌음을 알 수 있게 설정했습니다.
- 버튼 및 입력 폼 ui 디자인을 좀 더 깔끔하게 수정했습니다.
- 찾은 아이디를 보여주는 알림창을 추가했습니다.
- 아이디가 정상적으로 찾아졌을 경우 로그인 페이지로 이동하는 로직을 추가했습니다.
- 그 외 여러 에러 상황에서의 알림창 및 에러 처리를 추가했습니다.
- 필수 입력란에 입력을 하지 않았을 경우의 validation 및 에러 메시지를 추가했습니다.
=> 아이디 찾기 : 알림창 추가 및 코드 리팩토링

frontend/src/api/changePw.js, frontend/src/api/findPw.js, frontend/src/components/FindPwForm.js, frontend/src/components/ResetPwForm.js, frontend/src/hooks/useForm.js
구현 내용
- 리셋 링크 및 비밀번호 변경시 유저가 알 수 있도록 알림을 추가했습니다.
- 비밀번호 입력 및 이메일 입력 시 validation과 에러 메시지를 추가했습니다.
=> 비밀번호 찾기 : 코드 리팩토링 및 알림 추가

frontend/src/api/getField.js, frontend/src/components/Header.js, frontend/src/components/SearchBar.js, frontend/src/components/func/Select.js, frontend/src/constants/api.js, frontend/src/pages/AreaPage.jsx
- 배너 디자인 수정(캐릭터 + 분야)
- 검색창 디자인 수정(드롭다운 width 수정)
- 검색창 돋보기 버튼 기능 추가(돋보기 버튼 클릭시 search 되도록, 물론 엔터도 search 됨)
- 동아리 등록하기 버튼 cursor 추가(그 외 드롭다운, 돋보기 등등 cursor 추가)
- 검색 페이지 이동 시 해당 분야 모든 동아리 띄우기(field api 바로 호출, 만약 동아리가 없다면 띄우지 않음)
- width 줄이기(70vw)
- close #62
=> 검색 페이지 피드백 반영 완료

backend/routes/clubRoutes.js, frontend/package.json, frontend/src/api/deleteClub.js, frontend/src/api/postClub.js, frontend/src/api/putClub.js, frontend/src/components/Header.js, frontend/src/components/MyContents.js, frontend/src/components/MyInfo.js, frontend/src/components/RegisterClubContents.js, frontend/src/components/SignUpForm.js, frontend/src/components/club-detail/ClubActivity.js, frontend/src/components/club-detail/ClubContents.js, frontend/src/components/club-detail/ClubMember.js, frontend/src/components/club-edit/EditClubContents.js, frontend/src/hooks/useForm.js, frontend/src/index.js, frontend/src/pages/AreaPage.jsx, frontend/src/pages/LikePage.jsx
부득이하게 동아리 crud 피드백 branch에 좋아요 관리 페이지 작업도 이어서 했습니다.
- 동아리 crud 에러 해결
- 저번주 회의 피드백 반영
- 좋아요 페이지 생성
정상 작동 여부는 주말에 확인한 뒤 수정하겠습니다.
- close #66
=> 동아리글 crud 피드백 반영하기

backend/models/userModel.js, backend/routes/userRoutes.js
- 사용자 정보에서 전공, 재학 여부를 삭제하였습니다. 그리고 그에 따른 관련 API도 모두 수정 후 명세서에 반영해 놓았습니다. 
- close #68
=> 전공, 재학 여부 삭제

frontend/src/components/MyInfo.js, frontend/src/components/RegisterClubContents.js, frontend/src/hooks/useForm.js, frontend/src/pages/RegisterClubPage.jsx
=> fix: 에러 사항 수정

backend/models/clubModel.js, backend/package.json, backend/routes/clubRoutes.js, backend/routes/imageUploader.js
- 활동 소개 글 작성 20자 이상 제한 없앴습니다.
- 동아리 소개 글 작성, 수정, 삭제 api 수정하고 Postman에도 반영하였습니다. 
- 럼블은 해당 동아리 회장님이 직접 작성해주신 데이터라서 삭제하지 말아주세요!
- Postman documentation에 작성해 놓은 동아리 소개 글 작성, 수정 api 설명 잘 봐주세요!
- close #75
=> 이미지 저장 방식 변경

frontend/package.json, frontend/src/api/postClub.js, frontend/src/api/putClub.js, frontend/src/api/putUserInfo.js, frontend/src/components/RegisterClubContents.js, frontend/src/components/club-detail/ClubActivity.js, frontend/src/components/club-detail/ClubContents.js, frontend/src/components/club-detail/ClubIntro.js, frontend/src/components/club-edit/EditClubContents.js, frontend/src/components/func/ClubItem.js, frontend/src/constants/api.js, frontend/src/hooks/useForm.js, frontend/src/pages/AreaPage.jsx
- 동아리 회장 및 관리자에게만 버튼 보이게 설정(수정/삭제)
- 비율 깨짐 수정
- post api 수정
- put api 수정(추후 이어서 추가 작업 진행)
- 에러 메시지 수정
- topic에서 # 제거(req로 보낼때)
- 이미지 예외처리(부 이미지 보여주기)
- 텍스트 예외처리(디폴트 메시지 설정)
- 그외 자잘한 예외처리 추가
=> 에러 사항 및 수정 작업 진행

backend/routes/clubRoutes.js
=> 78 동아리 글 수정 api

backend/routes/clubRoutes.js
=> 82 activitytext1~4로 분리하기

frontend/src/api/postClub.js, frontend/src/api/putClub.js, frontend/src/components/RegisterClubContents.js, frontend/src/components/club-detail/ClubActivity.js, frontend/src/components/club-edit/EditClubContents.js
=> fix: 피드백 반영

backend/utili.js
비밀번호 재설정 링크 수정했습니다!
- close #87
=> 87 비밀번호 재설정 링크
